---
"$schema": http://json-schema.org/draft-04/hyper-schema
title: Site
definitions:
  id:
    description: unique identifier of site
    example: 1234567
    type:
    - integer
  identity:
    "$ref": "/schemata/site#/definitions/id"
  created_at:
    description: when site was created
    example: '2012-01-01T12:00:00Z'
    format: date-time
    type:
    - string
  updated_at:
    description: when site was updated
    example: '2012-01-01T12:00:00Z'
    format: date-time
    type:
    - string
  cname:
    description: The CNAME dns record.
    example: fundraising.betternow.org
    type:
      - string
  subdomain:
    description: The unique subdomain for this site.
    example: sample-event
    type:
      - string
  hostname:
    description: The hostname for this site.
    example: sample-event.eventsite.org
    type:
      - string
description: A website running the BetterNow software.
links:
  - description: List existing sites
    href: "/sites"
    method: GET
    rel: instances
    title: List
properties:
  cname:
    "$ref": "/schemata/site#/definitions/cname"
  created_at:
    "$ref": "/schemata/site#/definitions/created_at"
  id:
    "$ref": "/schemata/site#/definitions/id"
  hostname:
    "$ref": "/schemata/site#/definitions/hostname"
  subdomain:
    "$ref": "/schemata/site#/definitions/subdomain"
  updated_at:
    "$ref": "/schemata/site#/definitions/updated_at"
type:
  - object
id: schemata/site
